//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintManagementSystem
{

    public partial class ComplaintsList
    {

        protected global::System.Web.UI.WebControls.Image imgLogo;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl logoPlaceholder;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblWelcome;

        protected global::System.Web.UI.WebControls.Button btnAddNew;

        protected global::System.Web.UI.WebControls.Button btnUpdateComplaint;

        protected global::System.Web.UI.WebControls.Button btnLogout;

        protected global::System.Web.UI.WebControls.Panel pnlFilters;

        protected global::System.Web.UI.WebControls.Label lblSearchDescription;

        protected global::System.Web.UI.WebControls.TextBox txtSearchDescription;

        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;

        protected global::System.Web.UI.WebControls.DropDownList ddlFilterAssigned;

        protected global::System.Web.UI.WebControls.TextBox txtDateFrom;

        protected global::System.Web.UI.WebControls.TextBox txtDateTo;

        protected global::System.Web.UI.WebControls.DropDownList ddlSortBy;

        protected global::System.Web.UI.WebControls.Button btnApplyFilters;

        protected global::System.Web.UI.WebControls.Button btnClearFilters;

        protected global::System.Web.UI.WebControls.Button btnViewFullList;

        protected global::System.Web.UI.WebControls.Label lblFilterStatus;

        protected global::System.Web.UI.WebControls.Label lblFilterAssigned;

        protected global::System.Web.UI.WebControls.Label lblDateFrom;

        protected global::System.Web.UI.WebControls.Label lblDateTo;

        protected global::System.Web.UI.WebControls.Label lblSortBy;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.GridView gvComplaints;
    }
}


